# Generated by Django 4.0.4 on 2022-04-19 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('pointDepart', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('altitudeDepart', models.FloatField(verbose_name='Altitude de depart (m)')),
                ('altitudeMin', models.FloatField(verbose_name='Altitude minimale (m)')),
                ('altitudeMax', models.FloatField(verbose_name='Altitude maximale (m)')),
                ('denivPosCum', models.FloatField(verbose_name='Dénivelé Positif Cumulé (m)')),
                ('denivNegCum', models.FloatField(verbose_name='Dénivelé Negatif Cumulé (m)')),
                ('duree', models.TimeField()),
                ('difficulte', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)])),
            ],
        ),
    ]
