# Generated by Django 4.0.4 on 2022-04-21 08:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duree', models.TimeField()),
                ('nombrePersonnes', models.IntegerField(verbose_name='Nombre de personnes')),
                ('experience', models.CharField(choices=[('DEB', 'Debutants'), ('EXP', 'Experimentes'), ('MIX', 'Mixtes')], max_length=30)),
                ('meteo', models.CharField(choices=[('BON', 'Bonne'), ('MOY', 'Moyenne'), ('MAL', 'Mauvaise')], max_length=20)),
                ('difficulte', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=5)])),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
